### PR TITLE
Update to Opal 0.5.5

### PR DESCRIPTION
**Pull request by marcandre**
I think I didn't mess this up too badly.

### CODE REVIEW

**Comment by elia** [comment]
Awesome!

There's a typo in the coffee source, filename should have no quotes.

**Comment by elia** [comment]
Also be sure to include an updated version of lib/opal.js

**Comment by marcandre** [comment]
Actually, I messed up something else with the hash creation... brb

**Comment by marcandre** [comment]
Ok, this should work ok now.

When I get a chance I'll open a PR to modify Opal.hash so it accepts a plain object and Opal.compile so it accepts an option parameter (plain object or Hash).

**Comment by marcandre** [comment]
BTW, the lib/opal.js I included is the latest released (0.5.5). It's the first commit in the PR.

**Comment by elia** [comment]
Sorry my bad, I missed it because of the suppressed diff

**Comment by elia** [comment]
Merged manually a month ago

**Pull request closed without merging**
